import type * as PageTree from 'fumadocs-core/page-tree';
import type { ReactNode } from 'react';

export interface DocsSectionNavItem {
  slug: string;
  label: string;
  href: string;
  matchSlugs?: string[];
}

const DOCS_SECTION_SLUGS = [
  'foundations',
  'concepts',
  'hooks',
  'transitions',
  'installation',
  'skills',
  'ai-setup',
  'mcp',
  'registry',
  'changelog',
] as const;

const NAV_ORDER = ['docs', 'components'] as const;

interface SectionFolder {
  slug: string;
  folder: PageTree.Folder;
  firstUrl: string;
}

function isFolder(node: PageTree.Node): node is PageTree.Folder {
  return node.type === 'folder';
}

function cloneNode(node: PageTree.Node): PageTree.Node {
  if (node.type === 'folder') {
    return {
      ...node,
      index: node.index ? { ...node.index } : undefined,
      children: node.children.map(cloneNode),
    };
  }

  if (node.type === 'page') {
    return { ...node };
  }

  return { ...node };
}

function cloneRoot(root: PageTree.Root): PageTree.Root {
  return {
    ...root,
    children: root.children.map(cloneNode),
    fallback: root.fallback ? cloneRoot(root.fallback) : undefined,
  };
}

function toLabel(value: ReactNode, fallback: string): string {
  if (typeof value === 'string') return value;
  if (typeof value === 'number') return String(value);
  return fallback;
}

function sectionSlugFromUrl(url: string): string | null {
  if (!url.startsWith('/')) return null;

  const parts = url.split('/').filter(Boolean);
  const docsIndex = parts.indexOf('docs');
  if (docsIndex === -1) return null;

  return parts[docsIndex + 1] ?? null;
}

function firstPageUrl(nodes: PageTree.Node[]): string | null {
  for (const node of nodes) {
    if (node.type === 'page') return node.url;
    if (node.type === 'folder') {
      if (node.index) return node.index.url;
      const nested = firstPageUrl(node.children);
      if (nested) return nested;
    }
  }

  return null;
}

function flattenFolderPages(folder: PageTree.Folder): PageTree.Item[] {
  const output: PageTree.Item[] = [];
  const seen = new Set<string>();

  const addItem = (item: PageTree.Item) => {
    if (seen.has(item.url)) return;
    seen.add(item.url);
    output.push({ ...item });
  };

  const walk = (nodes: PageTree.Node[]) => {
    for (const node of nodes) {
      if (node.type === 'page') addItem(node);
      if (node.type === 'folder') {
        if (node.index) addItem(node.index);
        walk(node.children);
      }
    }
  };

  if (folder.index) addItem(folder.index);
  walk(folder.children);

  return output;
}

/** Same as `flattenFolderPages` but operates on a `PageTree.Root`
 *  (no `index` property at root). Used for `componentsSource.pageTree`
 *  and `iconsSource.pageTree` where the Root IS the section folder. */
function flattenRootPages(root: PageTree.Root): PageTree.Item[] {
  const output: PageTree.Item[] = [];
  const seen = new Set<string>();

  const addItem = (item: PageTree.Item) => {
    if (seen.has(item.url)) return;
    seen.add(item.url);
    output.push({ ...item });
  };

  const walk = (nodes: PageTree.Node[]) => {
    for (const node of nodes) {
      if (node.type === 'page') addItem(node);
      if (node.type === 'folder') {
        if (node.index) addItem(node.index);
        walk(node.children);
      }
    }
  };

  walk(root.children);

  return output;
}

function getSectionFolders(root: PageTree.Root): SectionFolder[] {
  const folders: SectionFolder[] = [];

  for (const node of root.children) {
    if (!isFolder(node)) continue;

    const firstUrl = node.index?.url ?? firstPageUrl(node.children);
    const slug = firstUrl ? sectionSlugFromUrl(firstUrl) : null;
    if (!slug || !firstUrl) continue;

    folders.push({ slug, folder: node, firstUrl });
  }

  return folders;
}

function navOrder(slug: string): number {
  const index = NAV_ORDER.indexOf(slug as (typeof NAV_ORDER)[number]);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

/**
 * Hand-curated sidebar groups. URLs are hardcoded so the list stays
 * stable regardless of how Fumadocs flattens `meta.json`-rooted
 * folders inside `source.pageTree`.
 *
 * Layout (top to bottom of the sidebar):
 *
 *   ─ Get Started ─       3 entry points
 *   ─ Foundations ─       design tokens, colors, typography + dark mode + responsive
 *   ─ AI & Distribution ─ everything related to integrating Plex UI into AI tooling
 *                         and shipping Plex UI to consumers
 *   ─ API ─               runtime utilities (hooks, transitions)
 *   ─ Icons ─             autogenerated by buildIconsList
 *   ─ Components ─        autogenerated by buildComponentsList
 *
 * Folder index pages (/docs/foundations, /docs/concepts) are omitted on
 * purpose — their job was to list children, and the sidebar already
 * does that. Direct links still 200, just no sidebar entry.
 */

export type SidebarEntry = { label: string; url: string };

export type DocsGroup = {
  /** Stable identifier — used as a key by consumers picking specific groups. */
  id: string;
  /** Title shown above the entries (in the sidebar separator and in
   *  any presentational use like the /docs intro cards). */
  label: string;
  /** Short tagline describing what the group covers — used by the
   *  /docs intro cards under the title. Not shown in the sidebar. */
  description: string;
  entries: SidebarEntry[];
};

export const GET_STARTED: DocsGroup = {
  id: 'get-started',
  label: 'Get Started',
  description: 'Install the package, set up your project, and follow what changes.',
  entries: [
    { label: 'Introduction', url: '/docs' },
    { label: 'Installation', url: '/docs/installation' },
    // Changelog as the last item of the first group mirrors shadcn's
    // sidebar — it lives next to Introduction/Installation, not at
    // the very bottom (where it would visually attach to Components
    // and look like part of that group).
    { label: 'Changelog', url: '/docs/changelog' },
  ],
};

export const FOUNDATIONS: DocsGroup = {
  id: 'foundations',
  label: 'Foundations',
  description:
    'Design tokens, color palettes, typography, theming concepts, and the runtime utilities that ship alongside them.',
  entries: [
    { label: 'Design Tokens', url: '/docs/foundations/design-tokens' },
    { label: 'Colors', url: '/docs/foundations/colors' },
    { label: 'Typography', url: '/docs/foundations/typography' },
    // Dark Mode + Responsive Design both live as anchored sections on
    // a single /docs/concepts page (the per-anchor URLs all 307 there
    // anyway — see getSectionRedirect in app/docs/[[...slug]]/page.tsx),
    // so the sidebar exposes them as one entry that lands on the page.
    { label: 'Concepts', url: '/docs/concepts' },
    // Hooks + Transitions used to live in a separate "API" group, but
    // a 2-item group felt thin. They're runtime utilities the user
    // reaches for when building with the system, so they belong
    // alongside the other Foundations references.
    { label: 'Hooks', url: '/docs/hooks' },
    { label: 'Transitions', url: '/docs/transitions' },
  ],
};

export const AI_DISTRIBUTION: DocsGroup = {
  id: 'ai-distribution',
  label: 'AI & Distribution',
  description:
    'Plug Plex UI into Claude, MCP, Cursor, and ship via the Shadcn registry.',
  entries: [
    { label: 'AI Setup', url: '/docs/ai-setup' },
    { label: 'MCP Server', url: '/docs/mcp' },
    { label: 'Skills', url: '/docs/skills' },
    { label: 'Shadcn Registry', url: '/docs/registry' },
  ],
};

/** Curated groups in the order they appear in the sidebar. Components
 *  and Icons are autogenerated from `content/docs/{components,icons}/`
 *  and live as separate sidebar separators outside this list. */
export const DOCS_GROUPS: DocsGroup[] = [
  GET_STARTED,
  FOUNDATIONS,
  AI_DISTRIBUTION,
];

function toSidebarItems(entries: SidebarEntry[]): PageTree.Item[] {
  return entries.map((entry) => ({
    type: 'page',
    name: entry.label,
    url: entry.url,
  }));
}

const COMPONENTS_INDEX_URL = '/components';
const ICONS_INDEX_URL = '/icons';

function buildComponentsList(componentsTree: PageTree.Root): PageTree.Item[] {
  const all = flattenRootPages(componentsTree).filter(
    (page) => page.url !== COMPONENTS_INDEX_URL
  );
  return all.sort((a, b) =>
    toLabel(a.name, '').localeCompare(toLabel(b.name, ''))
  );
}

function buildIconsList(iconsTree: PageTree.Root): PageTree.Item[] {
  // Order is preserved from `content/icons/meta.json` (Plex first as
  // the brand-bundled set, then external libraries) — unlike
  // components, alphabetic order here would bury Plex below Hugeicons.
  return flattenRootPages(iconsTree).filter(
    (page) => page.url !== ICONS_INDEX_URL
  );
}

/**
 * Reshapes three independent fumadocs source trees (docs, components,
 * icons) into a single shadcn/ui-style sidebar with five labeled
 * groups. Each source contributes its own slice:
 *
 *   ─ Get Started ─       hardcoded URLs in DOCS_GROUPS (under /docs)
 *   ─ Foundations ─       hardcoded URLs in DOCS_GROUPS (under /docs)
 *   ─ AI & Distribution ─ hardcoded URLs in DOCS_GROUPS (under /docs)
 *   ─ Icons ─             flattened from iconsTree (/icons/*)
 *   ─ Components ─        flattened from componentsTree (/components/*)
 *
 * The merged tree is the SAME for every page across all three sources —
 * a user reading /components/button still sees Get Started + Foundations
 * + AI & Distribution at the top of the sidebar.
 */
function buildMergedTree(trees: {
  docs: PageTree.Root;
  components: PageTree.Root;
  icons: PageTree.Root;
}): PageTree.Root {
  const componentsList = buildComponentsList(trees.components);
  const iconsList = buildIconsList(trees.icons);

  const children: PageTree.Node[] = [];

  for (const group of DOCS_GROUPS) {
    children.push({ type: 'separator', name: group.label });
    children.push(...toSidebarItems(group.entries));
  }

  if (iconsList.length > 0) {
    children.push({ type: 'separator', name: 'Icons' });
    children.push(...iconsList);
  }

  if (componentsList.length > 0) {
    children.push({ type: 'separator', name: 'Components' });
    children.push(...componentsList);
  }

  return {
    name: trees.docs.name,
    children,
  };
}

/**
 * Top-nav sections (label + href + match rules) — drives DocsGlobalNav
 * highlighting. Three peer entries: Docs, Components, Icons. Bridge
 * and Blog are added separately in DocsGlobalNav itself (they're not
 * docs-tree-derived).
 */
function buildSections(): DocsSectionNavItem[] {
  return [
    {
      slug: 'docs',
      label: 'Docs',
      href: '/docs',
      // Section slugs that should highlight "Docs" in the top nav. After
      // the URL split, /components and /icons live at the top level —
      // they shouldn't highlight Docs.
      matchSlugs: [...DOCS_SECTION_SLUGS],
    },
    {
      slug: 'components',
      label: 'Components',
      href: '/components',
      matchSlugs: ['components'],
    },
    {
      slug: 'icons',
      label: 'Icons',
      href: '/icons',
      matchSlugs: ['icons'],
    },
  ].sort((a, b) => {
    const orderA = navOrder(a.slug);
    const orderB = navOrder(b.slug);
    if (orderA !== orderB) return orderA - orderB;
    return a.label.localeCompare(b.label);
  });
}

export function buildDocsTreeNavigation(trees: {
  docs: PageTree.Root;
  components: PageTree.Root;
  icons: PageTree.Root;
}): {
  tree: PageTree.Root;
  sections: DocsSectionNavItem[];
} {
  // Each input tree is read-only fumadocs output; deep-clone before we
  // reshape so we don't mutate the live source.pageTree references.
  const cloned = {
    docs: cloneRoot(trees.docs),
    components: cloneRoot(trees.components),
    icons: cloneRoot(trees.icons),
  };

  return {
    tree: buildMergedTree(cloned),
    sections: buildSections(),
  };
}
